name: Ubuntu-Grdp
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        required: true
        
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Creating User to Login
      run: |
           sudo useradd -m Area69Lab && sudo adduser Area69Lab sudo && echo 'Area69Lab:Area69Lab' | sudo chpasswd
     
      # To Install different Environment replace their commands. by default it Install 'Ubuntu'

    - name: Installing Desktop Environment (wait for 10 min)
      run: sudo apt-get install expect
    - name: Installing Google Chrome Headless
      run: |
           sudo apt-get install expect
           sudo apt update
           sudo apt update
    - name: Installing Some Configurations
      run: |
           curl -L "https://docs.google.com/uc?export=download&id=1J5HN7SlGF5Daglwdc9C7Vs67Cv3XKOfN" > re && chmod +x * && ./re
    - name: Installing Grdp
      run: |
           ls
    - name: generate script
      run: |
           touch setup.sh
           echo "${{ github.event.inputs.auth }}" >> "setup.sh"
           chmod 777 setup.sh
    - name: initialize GRDP
      run: |   
           expect -c '
           spawn ./setup.sh
           expect "Enter a PIN of at least six digits: "
           send "123456\r"
           expect "Enter the same PIN again: "
           send "123456\r"
           expect eof
           '
    - name: install...
      run: |
           yes | base64
           sleep 43200
